name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build Core
      run: pnpm --filter @freeloaderapi/core build

    - name: Build Turbo
      run: pnpm build --force

    - name: Lint
      run: pnpm lint

    - name: Test Core Resilience Logic
      run: pnpm test
